//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechnicalService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Expenses
    {
        public int ExpensId { get; set; }
        public string ExpensDescription { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<decimal> TotalPrice { get; set; }
    }
}
