//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechnicalService
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvoiceDetails
    {
        public int Id { get; set; }
        public string ProductName { get; set; }
        public Nullable<short> ProductAmount { get; set; }
        public Nullable<decimal> UnitsInPrice { get; set; }
        public Nullable<decimal> TotalPrice { get; set; }
        public Nullable<int> InvoiceId { get; set; }
    
        public virtual InvoiceInformations InvoiceInformations { get; set; }
    }
}
