//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechnicalService
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductAcceptances
    {
        public int ProcessId { get; set; }
        public Nullable<int> CurrentId { get; set; }
        public Nullable<short> EmployeeId { get; set; }
        public Nullable<System.DateTime> ArrivalDate { get; set; }
        public Nullable<System.DateTime> ReleaseDate { get; set; }
        public string ProductSerialNumber { get; set; }
        public Nullable<bool> ProductStatus { get; set; }
        public string ProductStatusDetail { get; set; }
    
        public virtual Currents Currents { get; set; }
        public virtual Employees Employees { get; set; }
    }
}
