//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechnicalService
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductMovements
    {
        public byte Id { get; set; }
        public Nullable<byte> ProductId { get; set; }
        public Nullable<int> CurrentId { get; set; }
        public Nullable<short> EmployeeId { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<short> Amount { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string ProductSerialNumber { get; set; }
    
        public virtual Currents Currents { get; set; }
        public virtual Employees Employees { get; set; }
        public virtual Products Products { get; set; }
    }
}
